[package]
name = "OxideChat"
version = "0.2.0"
edition = "2024"
description = "A modern, performance and on customization focused AI chat application"
license = "MIT"
repository = "https://github.com/NxtCore/OxideChat"
readme = "README.md"
keywords = ["chat", "axum", "websocket", "postgres"]
categories = ["web-programming"]

[dependencies]
axum = { version = "0.8" }
tokio = { version = "1.48", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.9", features = [
    "postgres",
    "chrono",
    "tls-native-tls",
    "runtime-tokio",
    "macros",
    "migrate",
    "uuid",
    "rust_decimal",
] }
dotenv = { version = "0.15" }
argon2 = { version = "0.5" }
uuid = { version = "1.0", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
tower-cookies = { version = "0.11" }
arc-swap = "1.7.1"
oauth2 = "5"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
    "multipart",
] }
tower-http = { version = "0.5", features = ["cors"] }
omniference = "0.1.8"
aes-gcm = "0.10"
rand = "0.8"
rust_decimal = { version = "1.39.0", features = ["db-postgres", "serde"] }
futures-util = "0.3.31"
async-stream = "0.3.6"
tokio-util = "0.7.17"
extism = "1"
sha2 = "0.10"
base64 = "0.22"
thiserror = "2"
async-trait = "0.1"
infer = "0.16"

[lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
must_use_candidate = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
doc_markdown = "warn"
explicit_iter_loop = "warn"
explicit_into_iter_loop = "warn"
inconsistent_struct_constructor = "warn"
manual_let_else = "warn"
redundant_closure_for_method_calls = "warn"
semicolon_if_nothing_returned = "warn"
unnested_or_patterns = "warn"
unused_self = "warn"
cargo = { level = "warn", priority = -1 }
future_not_send = "warn"
fallible_impl_from = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
multiple_crate_versions = "allow"

[lints.rust]
unsafe_code = "warn"
missing_docs = "allow"
