ALTER TABLE teams ADD COLUMN IF NOT EXISTS default_model_key VARCHAR(255);

ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS default_provider_slug VARCHAR(255);
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS default_tools JSONB DEFAULT '[]';

INSERT INTO i18n_translations (language, key_path, value) VALUES
    ('en', 'settings.admin.default_model', 'Default model'),
    ('en', 'settings.admin.default_model_hint', 'Pre-select this model for all users when no team or personal default is set.'),
    ('en', 'settings.teams.default_model', 'Default model'),
    ('en', 'settings.teams.default_model_hint', 'Pre-select this model for team members. Overrides the global default.'),
    ('en', 'settings.teams.use_global_default', 'Use global default'),
    ('en', 'settings.profile.default_model', 'Default model'),
    ('en', 'settings.profile.default_model_hint', 'Pre-select this model when starting a new chat. Overrides team and global defaults.'),
    ('en', 'settings.profile.use_higher_default', 'Use team / global default'),
    ('de', 'settings.admin.default_model', 'Standardmodell'),
    ('de', 'settings.admin.default_model_hint', 'Dieses Modell für alle Benutzer vorauswählen, wenn kein Team- oder persönliches Standardmodell festgelegt ist.'),
    ('de', 'settings.teams.default_model', 'Standardmodell'),
    ('de', 'settings.teams.default_model_hint', 'Dieses Modell für Teammitglieder vorauswählen. Überschreibt das globale Standardmodell.'),
    ('de', 'settings.teams.use_global_default', 'Globalen Standard verwenden'),
    ('de', 'settings.profile.default_model', 'Standardmodell'),
    ('de', 'settings.profile.default_model_hint', 'Dieses Modell beim Starten eines neuen Chats vorauswählen. Überschreibt Team- und globale Standards.'),
    ('de', 'settings.profile.use_higher_default', 'Team- / globalen Standard verwenden'),
    ('en', 'chat.model_selector.toggle_default', 'Set as default model'),
    ('de', 'chat.model_selector.toggle_default', 'Als Standardmodell festlegen'),
    ('en', 'settings.profile.chat_defaults', 'Chat Defaults'),
    ('en', 'settings.profile.chat_defaults_description', 'Pre-configure model, provider, and tools for every new chat.'),
    ('en', 'settings.profile.default_provider', 'Default Provider'),
    ('en', 'settings.profile.default_provider_hint', 'Pre-select an upstream provider for the default model. Only visible for gateway models.'),
    ('en', 'settings.profile.default_provider_placeholder', 'Automatic'),
    ('en', 'settings.profile.default_tools', 'Default Tools'),
    ('en', 'settings.profile.default_tools_hint', 'These tools will be pre-enabled when starting a new chat.'),
    ('en', 'settings.profile.no_tools_available', 'No tools available. Connect an MCP server or add tools in the Tools settings.'),
    ('de', 'settings.profile.chat_defaults', 'Chat-Standardeinstellungen'),
    ('de', 'settings.profile.chat_defaults_description', 'Standardmäßiges Modell, Anbieter und Tools für jeden neuen Chat vorkonfigurieren.'),
    ('de', 'settings.profile.default_provider', 'Standard-Anbieter'),
    ('de', 'settings.profile.default_provider_hint', 'Einen vorgelagerten Anbieter für das Standardmodell vorauswählen. Nur für Gateway-Modelle sichtbar.'),
    ('de', 'settings.profile.default_provider_placeholder', 'Automatisch'),
    ('de', 'settings.profile.default_tools', 'Standard-Tools'),
    ('de', 'settings.profile.default_tools_hint', 'Diese Tools werden beim Starten eines neuen Chats vorausgewählt.'),
    ('de', 'settings.profile.no_tools_available', 'Keine Tools verfügbar. Verbinde einen MCP-Server oder füge Tools in den Tool-Einstellungen hinzu.'),
    ('en', 'settings.profile.save_success', 'Chat defaults saved.'),
    ('en', 'settings.profile.save_error', 'Failed to save chat defaults.'),
    ('de', 'settings.profile.save_success', 'Chat-Standardeinstellungen gespeichert.'),
    ('de', 'settings.profile.save_error', 'Chat-Standardeinstellungen konnten nicht gespeichert werden.'),
    ('en', 'chat.tool_selector.save_as_defaults', 'Save as defaults'),
    ('de', 'chat.tool_selector.save_as_defaults', 'Als Standard speichern'),
    ('en', 'chat.provider_selector.set_as_default', 'Set as default provider'),
    ('de', 'chat.provider_selector.set_as_default', 'Als Standard-Anbieter festlegen')
ON CONFLICT (language, key_path) DO NOTHING;
