CREATE TABLE IF NOT EXISTS budget_reset_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id UUID REFERENCES budget_assignments(id) ON DELETE CASCADE,
    budget_id UUID REFERENCES budgets(id) ON DELETE CASCADE,
    team_id UUID REFERENCES teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    kind budget_kind,
    reason TEXT,
    reset_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT budget_reset_events_scope_check CHECK (
        num_nonnulls(assignment_id, budget_id, team_id, user_id) = 1
    )
);

CREATE INDEX IF NOT EXISTS idx_budget_reset_events_assignment ON budget_reset_events(assignment_id, reset_at);
CREATE INDEX IF NOT EXISTS idx_budget_reset_events_budget ON budget_reset_events(budget_id, reset_at);
CREATE INDEX IF NOT EXISTS idx_budget_reset_events_team ON budget_reset_events(team_id, reset_at);
CREATE INDEX IF NOT EXISTS idx_budget_reset_events_user ON budget_reset_events(user_id, reset_at);

INSERT INTO i18n_translations (language, key_path, value) VALUES
    ('en', 'common.refresh', 'Refresh'),
    ('en', 'settings.budgets.tab_users', 'Users'),
    ('en', 'settings.budgets.tab_teams', 'Teams'),
    ('en', 'settings.budgets.tab_budgets', 'Budgets'),
    ('en', 'settings.budgets.tab_history', 'History'),
    ('en', 'settings.budgets.search_users', 'Search users'),
    ('en', 'settings.budgets.search_teams', 'Search teams'),
    ('en', 'settings.budgets.users_with_budgets', 'users'),
    ('en', 'settings.budgets.user', 'User'),
    ('en', 'settings.budgets.team', 'team'),
    ('en', 'settings.budgets.teams', 'Teams'),
    ('en', 'settings.budgets.members', 'members'),
    ('en', 'settings.budgets.effective_budgets', 'Effective budgets'),
    ('en', 'settings.budgets.status', 'Status'),
    ('en', 'settings.budgets.budget_count', 'budgets'),
    ('en', 'settings.budgets.no_user_budgets', 'No user budgets found'),
    ('en', 'settings.budgets.no_team_budgets', 'No team budgets found'),
    ('en', 'settings.budgets.no_reset', 'No reset'),
    ('en', 'settings.budgets.reset', 'Reset'),
    ('en', 'settings.budgets.affected_users', 'affected'),
    ('en', 'settings.budgets.settings', 'Settings'),
    ('en', 'settings.budgets.team_budget', 'team budget'),
    ('en', 'settings.budgets.user_budget', 'user budget'),
    ('en', 'settings.budgets.reset_at', 'Reset at'),
    ('en', 'settings.budgets.scope', 'Scope'),
    ('en', 'settings.budgets.budget', 'Budget'),
    ('en', 'settings.budgets.reason', 'Reason'),
    ('en', 'settings.budgets.reset_by', 'Reset by'),
    ('en', 'settings.budgets.no_reset_history', 'No reset history yet'),
    ('en', 'settings.budgets.reset_budget', 'Reset budget'),
    ('en', 'settings.budgets.kind_scope', 'Kind'),
    ('en', 'settings.budgets.all_kinds', 'All kinds'),
    ('en', 'settings.budgets.reason_placeholder', 'Optional note for the audit log'),
    ('en', 'settings.budgets.reset_keeps_history', 'Usage history is kept. This starts budget accounting from now for the selected scope.'),
    ('en', 'settings.budgets.assignment', 'Assignment'),
    ('en', 'settings.budgets.create_success', 'Budget created'),
    ('en', 'settings.budgets.create_error', 'Failed to create budget'),
    ('en', 'settings.budgets.save_success', 'Budget saved'),
    ('en', 'settings.budgets.save_error', 'Failed to save budget'),
    ('en', 'settings.budgets.delete_success', 'Budget deleted'),
    ('en', 'settings.budgets.delete_error', 'Failed to delete budget'),
    ('en', 'settings.budgets.assign_success', 'Budget assigned'),
    ('en', 'settings.budgets.assign_error', 'Failed to assign budget'),
    ('en', 'settings.budgets.remove_success', 'Assignment removed'),
    ('en', 'settings.budgets.remove_error', 'Failed to remove assignment'),
    ('en', 'settings.budgets.reset_success', 'Budget reset'),
    ('en', 'settings.budgets.reset_error', 'Failed to reset budget'),
    ('de', 'common.refresh', 'Aktualisieren'),
    ('de', 'settings.budgets.tab_users', 'Benutzer'),
    ('de', 'settings.budgets.tab_teams', 'Teams'),
    ('de', 'settings.budgets.tab_budgets', 'Budgets'),
    ('de', 'settings.budgets.tab_history', 'Historie'),
    ('de', 'settings.budgets.search_users', 'Benutzer suchen'),
    ('de', 'settings.budgets.search_teams', 'Teams suchen'),
    ('de', 'settings.budgets.users_with_budgets', 'Benutzer'),
    ('de', 'settings.budgets.user', 'Benutzer'),
    ('de', 'settings.budgets.team', 'Team'),
    ('de', 'settings.budgets.teams', 'Teams'),
    ('de', 'settings.budgets.members', 'Mitglieder'),
    ('de', 'settings.budgets.effective_budgets', 'Wirksame Budgets'),
    ('de', 'settings.budgets.status', 'Status'),
    ('de', 'settings.budgets.budget_count', 'Budgets'),
    ('de', 'settings.budgets.no_user_budgets', 'Keine Benutzerbudgets gefunden'),
    ('de', 'settings.budgets.no_team_budgets', 'Keine Teambudgets gefunden'),
    ('de', 'settings.budgets.no_reset', 'Kein Reset'),
    ('de', 'settings.budgets.reset', 'Zuruecksetzen'),
    ('de', 'settings.budgets.affected_users', 'betroffen'),
    ('de', 'settings.budgets.settings', 'Einstellungen'),
    ('de', 'settings.budgets.team_budget', 'Teambudget'),
    ('de', 'settings.budgets.user_budget', 'Benutzerbudget'),
    ('de', 'settings.budgets.reset_at', 'Reset um'),
    ('de', 'settings.budgets.scope', 'Bereich'),
    ('de', 'settings.budgets.budget', 'Budget'),
    ('de', 'settings.budgets.reason', 'Grund'),
    ('de', 'settings.budgets.reset_by', 'Zurueckgesetzt von'),
    ('de', 'settings.budgets.no_reset_history', 'Noch keine Reset-Historie'),
    ('de', 'settings.budgets.reset_budget', 'Budget zuruecksetzen'),
    ('de', 'settings.budgets.kind_scope', 'Art'),
    ('de', 'settings.budgets.all_kinds', 'Alle Arten'),
    ('de', 'settings.budgets.reason_placeholder', 'Optionale Notiz fuer das Audit-Log'),
    ('de', 'settings.budgets.reset_keeps_history', 'Die Nutzungshistorie bleibt erhalten. Die Budgetberechnung startet fuer diesen Bereich ab jetzt neu.'),
    ('de', 'settings.budgets.assignment', 'Zuweisung'),
    ('de', 'settings.budgets.create_success', 'Budget erstellt'),
    ('de', 'settings.budgets.create_error', 'Budget konnte nicht erstellt werden'),
    ('de', 'settings.budgets.save_success', 'Budget gespeichert'),
    ('de', 'settings.budgets.save_error', 'Budget konnte nicht gespeichert werden'),
    ('de', 'settings.budgets.delete_success', 'Budget geloescht'),
    ('de', 'settings.budgets.delete_error', 'Budget konnte nicht geloescht werden'),
    ('de', 'settings.budgets.assign_success', 'Budget zugewiesen'),
    ('de', 'settings.budgets.assign_error', 'Budget konnte nicht zugewiesen werden'),
    ('de', 'settings.budgets.remove_success', 'Zuweisung entfernt'),
    ('de', 'settings.budgets.remove_error', 'Zuweisung konnte nicht entfernt werden'),
    ('de', 'settings.budgets.reset_success', 'Budget zurueckgesetzt'),
    ('de', 'settings.budgets.reset_error', 'Budget konnte nicht zurueckgesetzt werden')
ON CONFLICT (language, key_path) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
