CREATE TABLE provider_billing_connections (
    provider_id UUID PRIMARY KEY REFERENCES providers(id) ON DELETE CASCADE,
    credential TEXT,
    external_scope_id TEXT,
    external_scope_name TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT false,
    last_status TEXT NOT NULL DEFAULT 'NOT_CONFIGURED',
    last_error_code TEXT,
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_billing_status_check CHECK (
        last_status IN ('NOT_CONFIGURED', 'AVAILABLE', 'UNSUPPORTED', 'UNAUTHORIZED', 'UPSTREAM_ERROR')
    )
);

CREATE TABLE provider_billing_snapshots (
    provider_id UUID PRIMARY KEY REFERENCES providers(id) ON DELETE CASCADE,
    metric_kind TEXT NOT NULL,
    currency TEXT NOT NULL,
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    limit_amount NUMERIC,
    spent_amount NUMERIC,
    remaining_amount NUMERIC,
    is_hard_limit BOOLEAN NOT NULL DEFAULT false,
    thresholds JSONB NOT NULL DEFAULT '[]'::jsonb,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    fetched_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT provider_billing_metric_kind_check CHECK (
        metric_kind IN ('CREDIT_BALANCE', 'KEY_LIMIT', 'SPEND_THRESHOLD', 'SPEND_ONLY')
    )
);

INSERT INTO i18n_translations (language, key_path, value) VALUES
    ('en', 'settings.providers.billing.tab', 'Billing'),
    ('en', 'settings.providers.billing.title', 'Billing overview'),
    ('en', 'settings.providers.billing.provider_reported', 'Provider reported'),
    ('en', 'settings.providers.billing.local_tracked', 'OxideChat tracked'),
    ('en', 'settings.providers.billing.setup_required', 'Billing setup required'),
    ('en', 'settings.providers.billing.unsupported', 'Unsupported by provider'),
    ('en', 'settings.providers.billing.failed', 'Last update failed'),
    ('en', 'settings.providers.billing.stale', 'Stale'),
    ('en', 'settings.providers.billing.spent_month', '{amount} spent this month'),
    ('en', 'settings.providers.billing.local_month', '{amount} this month'),
    ('en', 'settings.providers.billing.remaining_threshold', '{amount} remaining to the {threshold} threshold'),
    ('en', 'settings.providers.billing.over_threshold', 'Over threshold by {amount}'),
    ('en', 'settings.providers.billing.credits_remaining', '{amount} credits remaining'),
    ('en', 'settings.providers.billing.key_limit', 'Key limit: {amount}'),
    ('en', 'settings.providers.billing.threshold', 'Spend threshold'),
    ('en', 'settings.providers.billing.period', 'Period'),
    ('en', 'settings.providers.billing.refresh', 'Refresh'),
    ('en', 'settings.providers.billing.updated', 'Updated {time}'),
    ('en', 'settings.providers.billing.never_updated', 'Not refreshed yet'),
    ('en', 'settings.providers.billing.enable', 'Enable upstream billing'),
    ('en', 'settings.providers.billing.admin_key', 'OpenAI Admin API key'),
    ('en', 'settings.providers.billing.admin_key_hint', 'A separate organization Admin API key used only to read project costs.'),
    ('en', 'settings.providers.billing.project_id', 'OpenAI project ID'),
    ('en', 'settings.providers.billing.project_name', 'Project display name (optional)'),
    ('en', 'settings.providers.billing.management_key', 'OpenRouter management key (optional)'),
    ('en', 'settings.providers.billing.management_key_hint', 'Use an account management key for account-wide purchased and used credits. Without one, the inference key reports key-level usage.'),
    ('en', 'settings.providers.billing.encryption_required', 'Set ENCRYPTION_KEY before storing billing credentials.'),
    ('en', 'settings.providers.billing.local_only', 'OxideChat tracks local spend. This provider does not have a supported upstream billing integration.'),
    ('en', 'settings.providers.billing.remove', 'Remove billing connection'),
    ('en', 'settings.providers.billing.saved', 'Billing settings saved'),
    ('en', 'settings.providers.billing.removed', 'Billing connection removed'),
    ('en', 'settings.providers.billing.refresh_failed', 'Billing refresh failed'),
    ('de', 'settings.providers.billing.tab', 'Abrechnung'),
    ('de', 'settings.providers.billing.title', 'Abrechnungsuebersicht'),
    ('de', 'settings.providers.billing.provider_reported', 'Vom Anbieter gemeldet'),
    ('de', 'settings.providers.billing.local_tracked', 'Von OxideChat erfasst'),
    ('de', 'settings.providers.billing.setup_required', 'Abrechnung muss eingerichtet werden'),
    ('de', 'settings.providers.billing.unsupported', 'Vom Anbieter nicht unterstuetzt'),
    ('de', 'settings.providers.billing.failed', 'Letzte Aktualisierung fehlgeschlagen'),
    ('de', 'settings.providers.billing.stale', 'Veraltet'),
    ('de', 'settings.providers.billing.spent_month', '{amount} diesen Monat ausgegeben'),
    ('de', 'settings.providers.billing.local_month', '{amount} diesen Monat'),
    ('de', 'settings.providers.billing.remaining_threshold', '{amount} bis zum Schwellenwert von {threshold}'),
    ('de', 'settings.providers.billing.over_threshold', 'Schwellenwert um {amount} ueberschritten'),
    ('de', 'settings.providers.billing.credits_remaining', '{amount} Guthaben verbleibend'),
    ('de', 'settings.providers.billing.key_limit', 'Schluessellimit: {amount}'),
    ('de', 'settings.providers.billing.threshold', 'Ausgabenschwellenwert'),
    ('de', 'settings.providers.billing.period', 'Zeitraum'),
    ('de', 'settings.providers.billing.refresh', 'Aktualisieren'),
    ('de', 'settings.providers.billing.updated', 'Aktualisiert {time}'),
    ('de', 'settings.providers.billing.never_updated', 'Noch nicht aktualisiert'),
    ('de', 'settings.providers.billing.enable', 'Upstream-Abrechnung aktivieren'),
    ('de', 'settings.providers.billing.admin_key', 'OpenAI-Admin-API-Schluessel'),
    ('de', 'settings.providers.billing.admin_key_hint', 'Ein separater Organisations-Admin-Schluessel, der nur zum Lesen der Projektkosten verwendet wird.'),
    ('de', 'settings.providers.billing.project_id', 'OpenAI-Projekt-ID'),
    ('de', 'settings.providers.billing.project_name', 'Projekt-Anzeigename (optional)'),
    ('de', 'settings.providers.billing.management_key', 'OpenRouter-Management-Schluessel (optional)'),
    ('de', 'settings.providers.billing.management_key_hint', 'Ein Management-Schluessel zeigt kontoweite Guthaben und Ausgaben. Ohne diesen werden Daten des Inferenzschluessels verwendet.'),
    ('de', 'settings.providers.billing.encryption_required', 'ENCRYPTION_KEY muss gesetzt sein, bevor Abrechnungszugangsdaten gespeichert werden.'),
    ('de', 'settings.providers.billing.local_only', 'OxideChat erfasst lokale Ausgaben. Fuer diesen Anbieter gibt es keine unterstuetzte Upstream-Abrechnungsintegration.'),
    ('de', 'settings.providers.billing.remove', 'Abrechnungsverbindung entfernen'),
    ('de', 'settings.providers.billing.saved', 'Abrechnungseinstellungen gespeichert'),
    ('de', 'settings.providers.billing.removed', 'Abrechnungsverbindung entfernt'),
    ('de', 'settings.providers.billing.refresh_failed', 'Abrechnungsaktualisierung fehlgeschlagen')
ON CONFLICT (language, key_path) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
