-- Pending chat tooling and composer-state migration.

-- MCP (Model Context Protocol) support: instance config flag + UI translations.
INSERT INTO app_config (key, value)
VALUES ('allow_server_stdio_mcp', 'false')
ON CONFLICT (key) DO NOTHING;

INSERT INTO i18n_translations (language, key_path, value) VALUES
    ('en', 'sidebar.manage_mcp', 'Manage MCP servers'),
    ('en', 'mcp.manage_title', 'MCP servers'),
    ('en', 'mcp.manage_description', 'Connect remote Model Context Protocol servers to add tools to your chats.'),
    ('en', 'mcp.tool_selector.manage', 'Manage MCP servers…'),
    ('en', 'mcp.add', 'Add server'),
    ('en', 'mcp.edit', 'Edit'),
    ('en', 'mcp.delete', 'Delete'),
    ('en', 'mcp.save', 'Save'),
    ('en', 'mcp.cancel', 'Cancel'),
    ('en', 'mcp.name', 'Name'),
    ('en', 'mcp.name_placeholder', 'My MCP server'),
    ('en', 'mcp.transport', 'Transport'),
    ('en', 'mcp.transport_http', 'Streamable HTTP'),
    ('en', 'mcp.transport_stdio', 'stdio (server-side)'),
    ('en', 'mcp.url', 'Server URL'),
    ('en', 'mcp.url_placeholder', 'https://example.com/mcp'),
    ('en', 'mcp.headers', 'Headers (JSON)'),
    ('en', 'mcp.command', 'Command'),
    ('en', 'mcp.args', 'Arguments (one per line)'),
    ('en', 'mcp.enabled', 'Enabled'),
    ('en', 'mcp.discover', 'Test & discover tools'),
    ('en', 'mcp.discovered_tools', 'Discovered tools'),
    ('en', 'mcp.no_servers', 'No MCP servers yet.'),
    ('en', 'mcp.health', 'Health'),
    ('en', 'mcp.health_healthy', 'Healthy'),
    ('en', 'mcp.health_unhealthy', 'Unhealthy'),
    ('en', 'mcp.health_unknown', 'Unknown'),
    ('en', 'mcp.create_failed', 'Could not create the MCP server.'),
    ('en', 'mcp.update_failed', 'Could not update the MCP server.'),
    ('en', 'mcp.delete_failed', 'Could not delete the MCP server.'),
    ('en', 'mcp.discover_failed', 'Could not connect to the MCP server.'),
    ('en', 'admin.tools.mcp.allow_stdio', 'Allow server-side stdio MCP servers'),
    ('en', 'admin.tools.mcp.allow_stdio_hint', 'When enabled, global stdio MCP servers run arbitrary commands on the OxideChat host. Only enable on trusted, single-tenant instances.'),
    ('en', 'mcp.headers_name', 'Header name'),
    ('en', 'mcp.headers_value', 'Header value'),
    ('en', 'mcp.headers_add', 'Add header'),
    ('en', 'mcp.headers_empty', 'No headers added yet.'),
    ('en', 'mcp.headers_remove', 'Remove header'),
    ('en', 'chat.tool_selector.title', 'Tools'),
    ('en', 'chat.tool_selector.tools', 'tools'),
    ('en', 'chat.tool_selector.enabled', 'Enabled'),
    ('en', 'chat.tool_selector.available', 'Available'),
    ('en', 'chat.tool_selector.select_all', 'Select all'),
    ('en', 'chat.tool_selector.clear', 'Clear'),
    ('en', 'chat.tool_selector.no_tools', 'No tools available'),
    ('en', 'chat.tool_selector.no_tools_hint', 'Add an MCP server or a tool to get started.'),
    ('en', 'chat.tool_selector.count', '{count} selected'),
    ('en', 'chat.tool_selector.expand', 'Expand'),
    ('en', 'chat.tool_selector.collapse', 'Collapse'),
    ('en', 'chat.tool_selector.sub_tools', '{count} sub-tools'),
    ('en', 'chat.tool_selector.unknown_server', 'Unknown MCP server'),
    ('de', 'sidebar.manage_mcp', 'MCP-Server verwalten'),
    ('de', 'mcp.manage_title', 'MCP-Server'),
    ('de', 'mcp.manage_description', 'Verbinde entfernte Model-Context-Protocol-Server, um deinen Chats Werkzeuge hinzuzufügen.'),
    ('de', 'mcp.tool_selector.manage', 'MCP-Server verwalten…'),
    ('de', 'mcp.add', 'Server hinzufügen'),
    ('de', 'mcp.edit', 'Bearbeiten'),
    ('de', 'mcp.delete', 'Löschen'),
    ('de', 'mcp.save', 'Speichern'),
    ('de', 'mcp.cancel', 'Abbrechen'),
    ('de', 'mcp.name', 'Name'),
    ('de', 'mcp.name_placeholder', 'Mein MCP-Server'),
    ('de', 'mcp.transport', 'Transport'),
    ('de', 'mcp.transport_http', 'Streamable HTTP'),
    ('de', 'mcp.transport_stdio', 'stdio (serverseitig)'),
    ('de', 'mcp.url', 'Server-URL'),
    ('de', 'mcp.url_placeholder', 'https://example.com/mcp'),
    ('de', 'mcp.headers', 'Header (JSON)'),
    ('de', 'mcp.command', 'Befehl'),
    ('de', 'mcp.args', 'Argumente (eines pro Zeile)'),
    ('de', 'mcp.enabled', 'Aktiviert'),
    ('de', 'mcp.discover', 'Werkzeuge testen & finden'),
    ('de', 'mcp.discovered_tools', 'Gefundene Werkzeuge'),
    ('de', 'mcp.no_servers', 'Noch keine MCP-Server.'),
    ('de', 'mcp.health', 'Status'),
    ('de', 'mcp.health_healthy', 'Erreichbar'),
    ('de', 'mcp.health_unhealthy', 'Nicht erreichbar'),
    ('de', 'mcp.health_unknown', 'Unbekannt'),
    ('de', 'mcp.create_failed', 'Der MCP-Server konnte nicht erstellt werden.'),
    ('de', 'mcp.update_failed', 'Der MCP-Server konnte nicht aktualisiert werden.'),
    ('de', 'mcp.delete_failed', 'Der MCP-Server konnte nicht gelöscht werden.'),
    ('de', 'mcp.discover_failed', 'Verbindung zum MCP-Server fehlgeschlagen.'),
    ('de', 'admin.tools.mcp.allow_stdio', 'Serverseitige stdio-MCP-Server erlauben'),
    ('de', 'admin.tools.mcp.allow_stdio_hint', 'Wenn aktiviert, führen globale stdio-MCP-Server beliebige Befehle auf dem OxideChat-Host aus. Nur auf vertrauenswürdigen Einzelinstanzen aktivieren.'),
    ('de', 'mcp.headers_name', 'Header-Name'),
    ('de', 'mcp.headers_value', 'Header-Wert'),
    ('de', 'mcp.headers_add', 'Header hinzufügen'),
    ('de', 'mcp.headers_empty', 'Noch keine Header hinzugefügt.'),
    ('de', 'mcp.headers_remove', 'Header entfernen'),
    ('de', 'chat.tool_selector.title', 'Werkzeuge'),
    ('de', 'chat.tool_selector.tools', 'Werkzeuge'),
    ('de', 'chat.tool_selector.enabled', 'Aktiviert'),
    ('de', 'chat.tool_selector.available', 'Verfügbar'),
    ('de', 'chat.tool_selector.select_all', 'Alle auswählen'),
    ('de', 'chat.tool_selector.clear', 'Leeren'),
    ('de', 'chat.tool_selector.no_tools', 'Keine Werkzeuge verfügbar'),
    ('de', 'chat.tool_selector.no_tools_hint', 'Füge einen MCP-Server oder ein Werkzeug hinzu, um zu starten.'),
    ('de', 'chat.tool_selector.count', '{count} ausgewählt'),
    ('de', 'chat.tool_selector.expand', 'Ausklappen'),
    ('de', 'chat.tool_selector.collapse', 'Einklappen'),
    ('de', 'chat.tool_selector.sub_tools', '{count} Unterwerkzeuge'),
    ('de', 'chat.tool_selector.unknown_server', 'Unbekannter MCP-Server')
ON CONFLICT (language, key_path) DO UPDATE SET value = EXCLUDED.value;

ALTER TABLE messages
ADD COLUMN IF NOT EXISTS request_settings JSONB NOT NULL DEFAULT '{}';
